config/routes.rb
Bingo::Application.routes.draw do
  resources :albums do
    resources :photos
  end
  match "/images/uploads/*path" => "gridfs#serve"

  root :to => "home#index"

end

app/models/album.rb
class Album
  include Mongoid::Document
  field :name,    :type => String
  field :content, :type => String
  embeds_many :photos
end

app/models/photo.rb
require 'carrierwave/mongoid'

class Photo
  include Mongoid::Document
  field  :name,    :type => String
  field  :content, :type => String
  mount_uploader :image, ImageUploader
  embedded_in :album, :inverse_of => :photos
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all

    respond_to do |format|
      format.html # index.html.erb
      format.json {
        albums = @albums.entries.map do |album|
          {
            :id       => album.id,
            :photos   => album.photos.entries.map{ |photo| photo.id }
          }
        end
        render json: albums
      }
    end
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = Album.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/new
  # GET /albums/new.json
  def new
    @album = Album.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @album }
    end
  end

  # GET /albums/1/edit
  def edit
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(params[:album])

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render json: @album, status: :created, location: @album }
      else
        format.html { render action: "new" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /albums/1
  # PUT /albums/1.json
  def update
    @album = Album.find(params[:id])

    respond_to do |format|
      if @album.update_attributes(params[:album])
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :ok }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gridfs_controller.rb
require 'mongo'

class GridfsController < ActionController::Metal
  def serve
    gridfs_path = env["PATH_INFO"].gsub("/images/", "")
    begin
      gridfs_file = Mongo::GridFileSystem.new(Mongoid.database).open(gridfs_path, 'r')
      self.response_body = gridfs_file.read
      self.content_type = gridfs_file.content_type
    rescue
      self.status = :file_not_found
      self.content_type = 'text/plain'
      self.response_body = ''
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@albums = Album.all
  	@album = @albums.first
  	@photo = @albums.first.photos.first
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  # GET /albums/1/photos/1
  # GET /albums/1/photos/1.json
  def show

  	@album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])

    render :layout => 'photos'
  end

  # POST /albums/1/photos
  # POST /albums/1/photos.json
  def create
  	@album = Album.find(params[:album_id])
  	@photo = @album.photos.create!(params[:photo])
  	redirect_to @album, :notice => 'Photo created'
  end

  # DELETE /albums/1/photos/1
  # DELETE /albums/1/photos/1.json
  def destroy
  	@album = Album.find(params[:album_id])
    @photo = @album.photos.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :ok }
    end
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<h1>Listing photos</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
  </tr>

<% @album.photos.each do |photo| %>
  <tr>
    <td><%= photo.name %></td>
    <td><%= photo.content %></td>
    <td><%= link_to 'Destroy', [@album, photo], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<h2>Add a photo to the album</h2>
<%= form_for [@album, Photo.new] do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :image %><br />
	  <%= f.file_field :image %>
	</div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Listing albums</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @albums.each do |album| %>
  <tr>
    <td><%= album.name %></td>
    <td><%= album.content %></td>
    <td><%= link_to 'Show', album %></td>
    <td><%= link_to 'Edit', edit_album_path(album) %></td>
    <td><%= link_to 'Destroy', album, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @album.name %>
</p>

<p>
  <b>Content:</b>
  <%= @album.content %>
</p>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/home/index.html.erb
<div id="tree-view" class="demo">
  <ul>
    <% @albums.each_with_index do |album,i| %>
      <li id="albums_<%= album.id %>" <% if i==0 %>class="jstree-open"<% end %>>
        <a href="#"><%= album.name %></a>
        <ul>
          <% album.photos.each do |photo| %>
            <li id="albums_<%= album.id %>_photos_<%= photo.id %>">
              <a href="#"><%= photo.name %></a>
            </li>
          <% end %>
        </ul>
      </li>
    <% end %>
</div>

<div id="photo-view" class="spotlight-container">
</div

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bingo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.jstree" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/photos.html.erb
<%= javascript_include_tag "photos" %>

<%= yield %>

app/views/photos/show.html.erb
<div id="photo-view" class="spotlight-container">
  <div style="margin: 5%"  align="center">

    <% ############ Album title with arrows ############### %>
    <table>
      <table>
        <tr>
          <td>
            <%= image_tag "left.png", :size => "32x32", :id => 'prev_album' %>
          </td><td>
            <h2><%= @album.name %> album</h2>
          </td><td>
            <%= image_tag "right.png", :size => "32x32", :id => 'next_album' %>
          </td>
        </tr>
      </table>

    <% ############ Photo with arrows ############### %>
      <table>
        <tr>
          <td>
            <%= image_tag "left.png", :id => 'prev_photo'%>
          </td><td>
            <%= image_tag @photo.image.url, :size => "600x400" %>
          </td><td>
            <%= image_tag "right.png", :id => 'next_photo'%>
          </td>
        </tr>
      </table>

      <br>
      <%= @photo.content %>
    </table>

  </div>

</div>